
  <a href=#0 class=top>Top</a>
  <footer class="row footer text-muted">
   <div class="container">

    <?php if ($gcb_1 && isset($gcb[$gcb_1])): ?>
     <?php echo $gcb[$gcb_1]; ?>
    <?php else: ?>
     <p><span class=copyleft>&copy;</span><?php echo date("Y"); ?> <?php echo $settings['author']; ?><?php if ($type != 'news' && $type != 'search' && $type != 'notes'): ?>
      <br><?php echo $lang['page_last_modified']; ?><?php endif; ?><br>Powered by
      <a href="<?php echo HTP; ?>//demo-seite.com/path/to/phpsqlitecms/">phpSQLiteCMS</a>
     </p>
    <?php endif; ?>

    <!-- Github Stargazers -->
    <div id="github-container">
     <span class="github-button">
      <a class="github-action" target="_top" title="Star ztatement on Github" href="https://github.com/ztatement/phpsqlitecms">
       <svg viewBox="0 0 16 16"><path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.3 6.53 5.47 7.6.4.06.55-.18.55-.4 0-.18 0-.8 0-1.48-2.02.37-2.54-.5-2.7-.94-.1-.23-.48-.94-.82-1.13-.28-.15-.68-.52 0-.53.62 0 1.07.58 1.22.82.72 1.2 1.87.87 2.33.66.07-.52.28-.87.5-1.07-1.77-.2-3.63-.9-3.63-3.95 0-.87.3-1.6.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.2 2.2.83.64-.18 1.32-.27 2-.27.68 0 1.36.1 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.93.08 2.13.5.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.3.25.54.73.54 1.48 0 1.08 0 1.94 0 2.2 0 .22.15.47.55.4C13.7 14.52 16 11.52 16 8c0-4.42-3.58-8-8-8z"></path></svg>
       <span class=github-stars>Star</span>
      </a>
      <a class="github-count" target="_top" title="ztatement Stargazers" href="https://github.com/ztatement/phpsqlitecms/stargazers"><span class="counter">1</span></a>
     </span>
    </div><!-- ./Github Stargazers -->
    
    <br>

    <p class="float-xs-right">
     <a class="font-white" href="<?php echo BASE_URL; ?>cms/">.</a>
    </p>
   </div>
  </footer>

</div>
  
<!-- Bootstrap core JavaScript-->
<script src="<?php echo HTP; ?>//ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js" crossorigin="anonymous"></script>
<!---script>window.jQuery || document.write('<script src="<?php echo JQUERY; ?>"><\/script>');</script--->
<!--script async src="<?php echo HTP; ?>//cdnjs.cloudflare.com/ajax/libs/tether/1.2.0/js/tether.min.js" crossorigin="anonymous"></script-->
<script src="<?php echo TETHER; ?>" crossorigin="anonymous"></script>
<script async src="<?php echo HTP; ?>//maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.5/js/bootstrap.min.js" crossorigin="anonymous"></script>
<!---script>window.jQuery || document.write('<script src="<?php echo BOOTSTRAP; ?>"><\/script>');</script--->
<!--script src="<?php echo STATIC_URL; ?>js/holder.js"></script-->
<script src="<?php echo HOLDER; ?>" crossorigin="anonymous"></script>

<!--script src="<?php echo STATIC_URL; ?>js/core.min.js"></script-->
<script src="<?php echo STATIC_URL; ?>js/main.js"></script>
<?php if ($admin): ?>
 <script src="<?php echo STATIC_URL; ?>js/admin_frontend.js"></script>
<?php endif; ?>
<?php if (isset($contains_thumbnails)): ?>
 <script src="<?php echo STATIC_URL; ?>js/mylightbox.js" type="text/javascript"></script>
<?php endif; ?>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="<?php echo STATIC_URL; ?>js/ie10-viewport-bug-workaround.js"></script>
<script>
//jQuery to collapse the navbar on scroll
$(window).scroll(function() {
    if ($(".navbar").offset().top > 50) {
        $(".navbar-fixed-top").addClass("top-nav-collapse");
    } else {
        $(".navbar-fixed-top").removeClass("top-nav-collapse");
    }
});
//jQuery for page scrolling feature - requires jQuery Easing plugin
$(function() {
    $('a.page-scroll').bind('click', function(event) {
        var $anchor = $(this);
        $('html, body').stop().animate({
            scrollTop: $($anchor.attr('href')).offset().top
        }, 1500, 'easeInOutExpo');
        event.preventDefault();
    });
});

$(function () {
  Holder.addTheme("thumb", { background: "#55595c", foreground: "#eceeef", text: "Thumbnail" });
});

</script>

 </body>
</html>
<!-- Bootstrap core CSS -->
<link rel="stylesheet" href="<?php echo HTP; ?>//maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.5/css/bootstrap.min.css" crossorigin="anonymous">
<comment hidden>

</comment>
