<!DOCTYPE html>
<html lang="<?php echo $lang['lang']; ?>" dir="<?php echo $lang['dir']; ?>">
 <head>
  <meta charset="<?php echo $lang['charset']; ?>">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <title><?php if ($page_title): ?><?php echo $page_title; ?><?php else: ?><?php if ($title): ?><?php echo $title; ?> - <?php endif; ?><?php echo $settings['website_title']; ?><?php endif; ?></title>

  <meta name="description" content="<?php if ($description) {echo $description;} else {echo $settings['default_description'];} ?>">
  <meta name="keywords" content="<?php if ($keywords) {echo $keywords;} else {echo $settings['default_keywords'];} ?>">
  <meta name="generator" content="phpSQLiteCMS <?php echo $settings['version']; ?>">

  <!-- Custom styles for this template -->
  <!--link href="<?php //echo BOOTSTRAP_CSS; ?>" rel="stylesheet"-->
  <!--link href='<?php echo HTP; ?>//fonts.googleapis.com/css?family=Patua+One' rel='stylesheet' type='text/css'-->
  <link href="<?php echo STATIC_URL; ?>stylesheets/style.css" rel="stylesheet">
  <link rel=stylesheet href=<?php echo HTP; ?>//code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css crossorigin="anonymous">
  <link rel=stylesheet href=<?php echo HTP; ?>//cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css crossorigin="anonymous">
  <link rel="shortcut icon" href="<?php echo STATIC_URL; ?>img/favicon.png">
<style>

  /* Simply delete it for your own project. */
  #github-wrapper{max-height:3em;margin:0 auto;position:relative;text-align:center;width:100%}
  #github-container{background-color:#fff;margin-top:.67em}
  #github-container a{text-decoration:none}
  .github-button{background-color:#1d1e30;border:3px solid #1d1e30;display:inline-block;font-family:Arial,sans-serif;font-weight:700;letter-spacing:.15rem;text-transform:uppercase}
  .github-action{color:#fff;display:inline-block;float:left;font-size:1.33rem;line-height:32px;padding:10px 22px}
  .github-action:hover{color:#fff}
  .github-action svg{float:left;height:32px;margin-right:12px;width:32px}
  .github-action path{fill:#fff}
  .github-count{background-color:#fff;color:#1d1e30;display:inline-block;float:left;font-size:1.75rem;line-height:32px;padding:10px 30px}
  .github-action a{outline:medium none}
  .github-stars{color:#fff;}
  .github-button a:hover{color:#1d1e30}
  #github-container::after{clear:both;content:"";display:table}

</style>

 </head>